Refactor: Validation strict parameter
datagouv/fr-format pull request #14
Opened 2024-07-02 13:57 UTC by Sarrabah

2024-07-09 08:31 UTC, pierrecamilleri requested changes

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/common.py
> +        val = val.replace("  ", " ")
Utiliser une regex   (de mémoire `re.sub("\s+", " ")`)

Vérifier que ça remplace toutes les occurrences (`A  B  C` devient `A B C`)

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/enum_format.py
> +        May check with string normalization with the "options" of validation."""
`May preprocess the input and valid values according to given "options"`

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/geo/code_fantoir.py
> +    def is_valid(cls, value: str, options: Options = Options()) -> bool:
Supprimer l'argument "options"  si elles ne sont pas pris en compte.

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/enum_format.py
> +            normalized_enum = {normalize_value(e, options) for e in enum}
Gérer l'option "extra- valid-values" avant la normalisation, en les ajoutant à l'enum.

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/options.py
> +       The class Options is used to represent a list of necessary options to validate a French format.
```suggestion
       The class Options is used to represent a list of options to validate a French format.
```

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/options.py
> +        ignore_non_alphanumeric: Boolean
Penser à changer le nom dans la doc

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/common.py
> +    if options.ignore_extra_white_space is True:
```suggestion
    if options.ignore_extra_whitespace is True:
```

2024-07-09 08:31 UTC, pierrecamilleri commented on src/frformat/options.py
> +        ignore_extra_white_space: Boolean
Idem

2024-07-09 08:31 UTC, pierrecamilleri commented on src/tests/testing.py
>          lenient_test_cases: List[str],
Ok pour le moment. 
Peux-tu créer une issue qui indique que les options ne sont pas testées disjointement ?

2024-07-15 14:31 UTC, Sarrabah commented on src/frformat/enum_format.py
> +            normalized_enum = {normalize_value(e, options) for e in enum}
Je te remercie pour ta proposition visant à améliorer la performance de notre code. 
Effectivement, après ces modifications, le temps d'exécution des tests a été réduit de 15 minutes à environ 5 secondes.

2024-07-16 08:03 UTC, pierrecamilleri approved these changes
:pray:

2024-07-16 08:03 UTC, pierrecamilleri commented on src/frformat/nomenclature_acte_format.py
>          details = []
`is_valid_with_details` doit être, au même titre que `is_valid` une méthode d'instance.

2024-07-16 11:03 UTC, merged